
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package javaapplication9;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos {
  /* terminals */
  public static final int tpa = 6;
  public static final int tmenos = 3;
  public static final int televar = 8;
  public static final int EOF = 0;
  public static final int tpor = 4;
  public static final int tdecimal = 10;
  public static final int tnumero = 9;
  public static final int tmas = 2;
  public static final int tdivision = 5;
  public static final int error = 1;
  public static final int tpc = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tmas",
  "tmenos",
  "tpor",
  "tdivision",
  "tpa",
  "tpc",
  "televar",
  "tnumero",
  "tdecimal"
  };
}

