/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;

/**
 *
 * @author oscar
 */
public class tab extends javax.swing.JPanel{

    /**
     * Creates new form tab
     */
    
    private String nombre;
    private String path;
    int numlinea = 1;
    
    public tab() {
        initComponents();
        jScrollPane2.getVerticalScrollBar().setModel(jScrollPane1.getVerticalScrollBar().getModel());
        jScrollPane2.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        jScrollPane2.getHorizontalScrollBar().setPreferredSize(new Dimension(0,0));
        texto.addCaretListener(new CaretListener(){
            @Override
            public void caretUpdate(CaretEvent e) {
                int pos = e.getDot();
                try {
                    int fila = texto.getLineOfOffset(pos) + 1;
                    int columna = pos - texto.getLineStartOffset(fila - 1) + 1;
                    jLabel1.setText("Coordenada del cursor: Fila: " + fila + ", Columna: " + columna);
                } catch (BadLocationException ex) {
                    
                }
            }
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(847, 496));

        texto.setColumns(20);
        texto.setRows(5);
        texto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textoPropertyChange(evt);
            }
        });
        texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(texto);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(4);
        jTextArea1.setRows(5);
        jTextArea1.setText("1");
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setText("Coordenada del cursor: Fila: , Columna:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    boolean control = false;
    
    private void textoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            numlinea++;
            jTextArea1.append("\n" + numlinea);
        }
        if(evt.getKeyCode() == KeyEvent.VK_PASTE){
            numlinea = texto.getLineCount();
            jTextArea1.setText("1");
            for(int i = 1; i < numlinea; i++){
                jTextArea1.append("\n" + (i+1));
            }
            control = false;
        }
    }//GEN-LAST:event_textoKeyPressed

    private void textoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            numlinea = texto.getLineCount();
            jTextArea1.setText("1");
            for(int i = 1; i < numlinea; i++){
                jTextArea1.append("\n" + (i+1));
            }
        }
        if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            numlinea = texto.getLineCount();
            jTextArea1.setText("1");
            for(int i = 1; i < numlinea; i++){
                jTextArea1.append("\n" + (i+1));
            }
        }
    }//GEN-LAST:event_textoKeyReleased
    
    private void textoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the path
     */
    public String getPath() {
        return path;
    }

    /**
     * @param path the path to set
     */
    public void setPath(String path) {
        this.path = path;
    }
    
    public void setTexto(String texto){
        this.texto.setText(texto);
        numlinea = this.texto.getLineCount();
        for(int i = 1; i < numlinea; i++){
            jTextArea1.append("\n" + (i+1));
        }
    }
    
    public JTextArea getTexto(){
        return this.texto;
    }
}
