
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cliente;

/** CUP generated class containing symbol constants. */
public class tabla_sim_cpreport {
  /* terminals */
  public static final int tparametros = 70;
  public static final int tpuntoycoma = 29;
  public static final int tigual = 50;
  public static final int tboolean = 37;
  public static final int ttitulo = 7;
  public static final int ttextcolor = 18;
  public static final int tmas = 41;
  public static final int tor = 53;
  public static final int tfont = 20;
  public static final int tclases = 32;
  public static final int tmultiplicacion = 44;
  public static final int tid = 57;
  public static final int tmenorigual = 48;
  public static final int tmodulo = 45;
  public static final int tcantidad = 30;
  public static final int tclase = 69;
  public static final int tcadena = 59;
  public static final int tmetodos = 31;
  public static final int ttable = 9;
  public static final int tparrafo = 14;
  public static final int tmenor = 3;
  public static final int tdivision = 43;
  public static final int tint = 33;
  public static final int tbr = 15;
  public static final int tmayorigual = 49;
  public static final int tcolor = 17;
  public static final int tmayor = 2;
  public static final int tdiagonal = 65;
  public static final int ttrue = 38;
  public static final int thr = 16;
  public static final int tnot = 54;
  public static final int tand = 52;
  public static final int tvariables = 24;
  public static final int tcoma = 62;
  public static final int tiniciocpreport = 64;
  public static final int tcomentariomulti = 61;
  public static final int tpunto = 25;
  public static final int ttitle = 8;
  public static final int EOF = 0;
  public static final int tcomentario = 60;
  public static final int ttr = 12;
  public static final int tdiv = 13;
  public static final int error = 1;
  public static final int thead = 5;
  public static final int tnum = 66;
  public static final int tstring = 36;
  public static final int tfloat = 35;
  public static final int tasignar = 40;
  public static final int tth = 10;
  public static final int ttexto = 63;
  public static final int ttd = 11;
  public static final int tfalse = 39;
  public static final int tresult = 22;
  public static final int tfuncion = 68;
  public static final int tdolar = 21;
  public static final int tnumero = 56;
  public static final int talign = 19;
  public static final int tbody = 6;
  public static final int tprint = 55;
  public static final int tcaracter = 58;
  public static final int tcorchetecerrar = 27;
  public static final int tcorcheteabrir = 26;
  public static final int thtml = 4;
  public static final int tnombre = 28;
  public static final int tparentesisabrir = 46;
  public static final int tnoigual = 51;
  public static final int tscore = 23;
  public static final int tparentesiscerrar = 47;
  public static final int tresta = 42;
  public static final int ttipo = 67;
  public static final int tchar = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tmayor",
  "tmenor",
  "thtml",
  "thead",
  "tbody",
  "ttitulo",
  "ttitle",
  "ttable",
  "tth",
  "ttd",
  "ttr",
  "tdiv",
  "tparrafo",
  "tbr",
  "thr",
  "tcolor",
  "ttextcolor",
  "talign",
  "tfont",
  "tdolar",
  "tresult",
  "tscore",
  "tvariables",
  "tpunto",
  "tcorcheteabrir",
  "tcorchetecerrar",
  "tnombre",
  "tpuntoycoma",
  "tcantidad",
  "tmetodos",
  "tclases",
  "tint",
  "tchar",
  "tfloat",
  "tstring",
  "tboolean",
  "ttrue",
  "tfalse",
  "tasignar",
  "tmas",
  "tresta",
  "tdivision",
  "tmultiplicacion",
  "tmodulo",
  "tparentesisabrir",
  "tparentesiscerrar",
  "tmenorigual",
  "tmayorigual",
  "tigual",
  "tnoigual",
  "tand",
  "tor",
  "tnot",
  "tprint",
  "tnumero",
  "tid",
  "tcaracter",
  "tcadena",
  "tcomentario",
  "tcomentariomulti",
  "tcoma",
  "ttexto",
  "tiniciocpreport",
  "tdiagonal",
  "tnum",
  "ttipo",
  "tfuncion",
  "tclase",
  "tparametros"
  };
}

