
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cliente;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos_json {
  /* terminals */
  public static final int tscore = 7;
  public static final int tclase = 13;
  public static final int tparametros = 15;
  public static final int tclases = 8;
  public static final int tcorcheteabrir = 4;
  public static final int ttexto = 20;
  public static final int tdospuntos = 19;
  public static final int tmetodos = 14;
  public static final int EOF = 0;
  public static final int tcadena = 18;
  public static final int tnombre = 9;
  public static final int tcomentarios = 16;
  public static final int ttipo = 11;
  public static final int error = 1;
  public static final int tnumero = 17;
  public static final int tvariables = 10;
  public static final int tcoma = 6;
  public static final int tllaveabrir = 2;
  public static final int tfuncion = 12;
  public static final int tcorchetecerrar = 5;
  public static final int tllavecerrar = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tllaveabrir",
  "tllavecerrar",
  "tcorcheteabrir",
  "tcorchetecerrar",
  "tcoma",
  "tscore",
  "tclases",
  "tnombre",
  "tvariables",
  "ttipo",
  "tfuncion",
  "tclase",
  "tmetodos",
  "tparametros",
  "tcomentarios",
  "tnumero",
  "tcadena",
  "tdospuntos",
  "ttexto"
  };
}

