
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package practica1_201220165;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos {
  /* terminals */
  public static final int telseif = 40;
  public static final int tcase = 49;
  public static final int tboolean = 13;
  public static final int tigual = 5;
  public static final int tsub = 31;
  public static final int tselect = 48;
  public static final int tmas = 19;
  public static final int tor = 56;
  public static final int tuntil = 47;
  public static final int treturn = 50;
  public static final int tif = 38;
  public static final int tpor = 27;
  public static final int tid = 59;
  public static final int tmenorigual = 52;
  public static final int tbyval = 32;
  public static final int tparabrir = 29;
  public static final int tcadena = 60;
  public static final int tmenos = 20;
  public static final int tmenor = 51;
  public static final int tloop = 46;
  public static final int tnext = 42;
  public static final int texit = 34;
  public static final int tmain = 64;
  public static final int tmodule = 2;
  public static final int tfor = 36;
  public static final int tmayorigual = 54;
  public static final int twriteline = 37;
  public static final int tmayor = 53;
  public static final int tcorcerrar = 8;
  public static final int ttrue = 25;
  public static final int tnot = 57;
  public static final int tand = 55;
  public static final int tcoma = 7;
  public static final int tfunction = 33;
  public static final int tpunto = 23;
  public static final int EOF = 0;
  public static final int tpublic = 9;
  public static final int treadline = 24;
  public static final int twhile = 35;
  public static final int terrorlexico = 61;
  public static final int tdiv = 28;
  public static final int error = 1;
  public static final int tto = 43;
  public static final int tconsole = 22;
  public static final int tstring = 18;
  public static final int telse = 41;
  public static final int tdim = 11;
  public static final int tfalse = 26;
  public static final int tas = 4;
  public static final int tthen = 39;
  public static final int tnumero = 58;
  public static final int tprivate = 10;
  public static final int tcorabierto = 6;
  public static final int tlong = 17;
  public static final int tinteger = 16;
  public static final int tdo = 45;
  public static final int tcom = 62;
  public static final int tdiferente = 63;
  public static final int tparcerrar = 30;
  public static final int tstep = 44;
  public static final int tdouble = 15;
  public static final int tend = 3;
  public static final int tstatic = 12;
  public static final int tchar = 14;
  public static final int tconcate = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tmodule",
  "tend",
  "tas",
  "tigual",
  "tcorabierto",
  "tcoma",
  "tcorcerrar",
  "tpublic",
  "tprivate",
  "tdim",
  "tstatic",
  "tboolean",
  "tchar",
  "tdouble",
  "tinteger",
  "tlong",
  "tstring",
  "tmas",
  "tmenos",
  "tconcate",
  "tconsole",
  "tpunto",
  "treadline",
  "ttrue",
  "tfalse",
  "tpor",
  "tdiv",
  "tparabrir",
  "tparcerrar",
  "tsub",
  "tbyval",
  "tfunction",
  "texit",
  "twhile",
  "tfor",
  "twriteline",
  "tif",
  "tthen",
  "telseif",
  "telse",
  "tnext",
  "tto",
  "tstep",
  "tdo",
  "tloop",
  "tuntil",
  "tselect",
  "tcase",
  "treturn",
  "tmenor",
  "tmenorigual",
  "tmayor",
  "tmayorigual",
  "tand",
  "tor",
  "tnot",
  "tnumero",
  "tid",
  "tcadena",
  "terrorlexico",
  "tcom",
  "tdiferente",
  "tmain"
  };
}

